version: "3"
services:
  db:
    container_name: db
    image: neo4j:latest
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/src
